model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-turbo
    litellm_params:
      model: openai/gpt-4-turbo # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-turbo-preview
    litellm_params:
      model: openai/gpt-4-turbo-preview # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-0125-preview
    litellm_params:
      model: openai/gpt-4-0125-preview # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-vision-preview
    litellm_params:
      model: openai/gpt-4-vision-preview # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4 # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-32k
    litellm_params:
      model: openai/gpt-4-32k # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo-instruct
    litellm_params:
      model: text-completion-openai/gpt-3.5-turbo-instruct # The `text-completion-openai/` prefix will call openai.completions.create
      api_key: os.environ/OPENAI_API_KEY
  - model_name: "*" # all requests where model not in your config go to this deployment
    litellm_params:
      model: openai/* # set `openai/` to use the openai route
      api_key: os.environ/OPENAI_API_KEY

  - model_name: azure-gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_key: os.environ/AZURE_API_KEY
      api_base: os.environ/AZURE_API_BASE
      api_version: os.environ/AZURE_API_VERSION
  - model_name: azure-gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-35-turbo
      api_key: os.environ/AZURE_API_KEY
      api_base: os.environ/AZURE_API_BASE
      api_version: os.environ/AZURE_API_VERSION
  - model_name: azure-gpt-3.5-turbo-instruct
    litellm_params:
      model: azure/gpt-35-turbo-instruct
      api_key: os.environ/AZURE_API_KEY
      api_base: os.environ/AZURE_API_BASE
      api_version: os.environ/AZURE_API_VERSION
  - model_name: azure-gpt-3.5-turbo-16k
    litellm_params:
      model: azure/gpt-35-turbo-16k
      api_key: os.environ/AZURE_API_KEY
      api_base: os.environ/AZURE_API_BASE
      api_version: os.environ/AZURE_API_VERSION

  - model_name: claude-3.5-sonnet
    litellm_params:
      model: claude-3-5-sonnet-20240620
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-haiku
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-opus
    litellm_params:
      model: claude-3-opus-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-sonnet
    litellm_params:
      model: claude-3-sonnet-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-2
    litellm_params:
      model: claude-2
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-2.1
    litellm_params:
      model: claude-2.1
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-instant-1.2
    litellm_params:
      model: claude-instant-1.2
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: bedrock-claude-1
    litellm_params:
      model: bedrock/anthropic.claude-instant-v1
  - model_name: bedrock-claude-2
    litellm_params:
      model: bedrock/anthropic.claude-v2
  - model_name: bedrock-claude-2.1
    litellm_params:
      model: bedrock/anthropic.claude-v2:1
  - model_name: bedrock-claude-3.5-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
  - model_name: bedrock-claude-3-haiku
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0
  - model_name: bedrock-claude-3-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
  - model_name: bedrock-claude-3-opus
    litellm_params:
      model: bedrock/anthropic.claude-3-opus-20240229-v1:0

  - model_name: bedrock-llama2-13b-chat
    litellm_params:
      model: bedrock/meta.llama2-13b-chat-v1
  - model_name: bedrock-llama2-70b-chat
    litellm_params:
      model: bedrock/meta.llama2-70b-chat-v1
  - model_name: bedrock-llama3-8b-instruct
    litellm_params:
      model: bedrock/meta.llama3-8b-instruct-v1:0
  - model_name: bedrock-llama3-70b-instruct
    litellm_params:
      model: bedrock/meta.llama3-70b-instruct-v1:0

  - model_name: bedrock-mistral-7b-instruct
    litellm_params:
      model: bedrock/mistral.mistral-7b-instruct-v0:2
  - model_name: bedrock-mistral-small
    litellm_params:
      model: bedrock/mistral.mistral-small-2402-v1:0
  - model_name: bedrock-mistral-large
    litellm_params:
      model: bedrock/mistral.mistral-large-2402-v1:0
  - model_name: bedrock-mixtral-7x7b-instruct
    litellm_params:
      model: bedrock/mistral.mixtral-8x7b-instruct-v0:1

  - model_name: vllm-llama3-8b-instruct
    litellm_params:
      model: openai/llama3-8b-instruct
      api_base: http://vllm-service-llama3-8b-instruct.vllm/v1/
